export const RECIPE_ADD = 'RECIPE_ADD';
export const RECIPE_REMOVE = 'RECIPE_REMOVE';
export const RECIPE_EDIT = 'RECIPE_EDIT';
export const RECIPE_ADD_INGREDIENT = 'RECIPE_ADD_INGREDIENT';
export const RECIPE_REMOVE_INGREDIENT = 'RECIPE_REMOVE_INGREDIENT';
